application: hartmanauctioneering
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img  

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py